eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server:8002/eureka

config:
  oauth2:
    clientId: client
    clientSecret: secret
    url: http://auth-server:8001
  service:
    global:
      url: http://global-service:8004
    committee:
      url: http://committee:8005
    usm:
      url: http://user-management:8003

jwt:
  secret: BvPHGM8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByY
  expirationTime: 1200    # 7200: 2 hours for development only

spring:
  datasource:
    url: jdbc:postgresql://devmuhsnashik.dcservices.in:5432/muhs_nashik
    username: muhsnashik
    password: MuHs123NaShIk
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: none
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 5MB
      max-request-size: 200MB

ftp:
  url: devmuhsnashik01.dcservices.in
  username: ftpuser1
  password: ftpuser1!


logging:
  level:
    root: "info"
    org.springframework.web: "info"
    org.springframework.security: "info"
    org.hibernate: "info"
