eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server:8002/eureka

config:
  oauth2:
    clientId: client
    clientSecret: secret
    url: http://auth-server:8001
  service:
    global:
      url: http://global-service:8004
    committee:
      url: http://committee:8005
    usm:
      url: http://user-management:8003
    pb:
      url: http://planning-board:8006

jwt:
  secret: BvPHGM8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByY
  expirationTime: 1200     # 15 Minutes

spring:
  datasource:
    url: jdbc:postgresql://uatmuhsnashik01.dcservices.in:6432/muhs_nashik
    username: muhsnashik
    password: MuHs123NaShIk
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: muhs-CP
      maximum-pool-size: 50
      connection-timeout: 30000
      initialization-fail-timeout: 45000
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: none
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 5MB
      max-request-size: 200MB
#  cloud:
#    gateway:
#      default-filters:
#        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
#      globalcors:
#        cors-configurations:
#          '[/**]':
#            allowedOrigins: "*"
#            allowedMethods:
#              - GET
#              - POST
#              - DELETE
#              - PUT
#              - PATCH
#            allowedHeaders:
#              - Authorization
#              - content-type
#              - fhttf
#              - f_code

ftp:
  url: 10.10.10.168
  username: ftpuser1
  password: ftpuser1!

logging:
  level:
    root: "info"
    org.springframework.web: "info"
    org.springframework.security: "info"
    org.hibernate: "info"
