eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8002/eureka

config:
  oauth2:
    clientId: client
    clientSecret: secret
    url: http://localhost:8001
  service:
    global:
      url: http://localhost:8004
    committee:
      url: http://localhost:8005

jwt:
  secret: BvPHGM8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByY
  expirationTime: 1200    # 7200: 2 hours for development only

spring:
  datasource:
    url: jdbc:postgresql://devmuhsnashik.dcservices.in:5432/muhs_nashik
    username: muhsnashik
    password: MuHs123NaShIk
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: none

logging:
  level:
    root: "info"
    org.springframework.web: "info"
    org.springframework.security: "info"
    org.hibernate: "info"
