eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8002/eureka
  instance:
    hostname: localhost

config:
  oauth2:
    clientId: client
    clientSecret: secret
    url: http://localhost:8001
  service:
    global:
      url: http://localhost:8004
    committee:
      url: http://localhost:8005
    usm:
      url: http://localhost:8003
    pb:
      url: http://localhost:8006

jwt:
  secret: BvPHGM8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByY
  expirationTime: 7200    # 7200: 2 hours for development only

spring:
  datasource:
    url: jdbc:postgresql://10.226.80.87:5432/muhs_nashik
    username: muhsnashik
    password: MuHs123NaShIk
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: muhs-CP
      maximum-pool-size: 50
      minimum-idle: 5
      connection-timeout: 30000       # 30 seconds
      initialization-fail-timeout: 45000      # 45 seconds
      idle-timeout: 60000     # 1 minute
      keepalive-time: 90000   # 1 minute 30 seconds
      max-lifetime: 240000    # 4 minutes

  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: none
    open-in-view: false
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 50MB
      max-request-size: 200MB
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - PATCH
            allowedHeaders:
              - Authorization
              - content-type
              - fhttf
              - f_code

ftp:
  url: 10.226.80.182
  username: ftpuser1
  password: ftpuser1!


logging:
  level:
    root: "info"
    org.springframework.web: "info"
    org.springframework.security: "info"
    org.hibernate: "info"
    #com.zaxxer.hikari: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: '*'
    health:
      show-details: "always"