server:
  port: 8180

spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8888"
  profiles:
    active:
      - dev
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - PATCH
            allowedHeaders:
              - Authorization
              - content-type
              - fhttf
              - f_code
  codec:
    max-in-memory-size: 20MB
