server:
  port: 8180

spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8888"
  profiles:
    active:
      - dev

  codec:
    max-in-memory-size: 20MB
