server:
  port: 8180

spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8888"
  profiles:
    active:
      - dev
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
#  cloud:
#      routes:
#    gateway:
#        - id: user-management
#          predicates:
#          uri: lb://user-management
#            - Path=/usm/**

