spring:
  application:
    name: global-service
  config:
    import: "optional:configserver:"
  profiles:
    active:
      - dev
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true

server:
  port: 8004

logging:
  level:
    root: "debug"
    org.springframework.web: "debug"
    org.springframework.security: "debug"
    org.hibernate: "info"
