spring:
  application:
    name: global-service
  config:
    import: "optional:configserver:"
  profiles:
    active:
      - dev
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true

server:
  port: 8004
